#!/bin/bash
### ---
### name: 'FEATURECOUNTS'
### container: 'pierrejeangouze/featurecounts:1.4.6-p3'
### outputs:
### - 'counts.txt'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /home/grani/nextflow_work/compil_deseq2/work/18/00c4d88162bc6c2e99dbf9918f133f/.exitcode
    set +u
    docker rm $NXF_BOXID &>/dev/null || true
    exit $exit_status
}

on_term() {
    set +e
    docker stop $NXF_BOXID
}

nxf_launch() {
    docker run -i --cpu-shares 1024 -e "NXF_TASK_WORKDIR" -v /home/grani/nextflow_work/compil_deseq2/work:/home/grani/nextflow_work/compil_deseq2/work -w "$NXF_TASK_WORKDIR" --entrypoint '' --name $NXF_BOXID pierrejeangouze/featurecounts:1.4.6-p3 /bin/bash -ue /home/grani/nextflow_work/compil_deseq2/work/18/00c4d88162bc6c2e99dbf9918f133f/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f SRR10379724_1_trimmed.bam
    rm -f SRR10379723_1_trimmed.bam
    rm -f SRR10379725_1_trimmed.bam
    rm -f SRR10379722_1_trimmed.bam
    rm -f SRR10379726_1_trimmed.bam
    rm -f SRR10379721_1_trimmed.bam
    rm -f reference.gff
    ln -s /home/grani/nextflow_work/compil_deseq2/work/42/e3331e7b6a6d8e43d53869379152b7/SRR10379724_1_trimmed.bam SRR10379724_1_trimmed.bam
    ln -s /home/grani/nextflow_work/compil_deseq2/work/74/ed8e94d0bb92698da9cb2e954cff47/SRR10379723_1_trimmed.bam SRR10379723_1_trimmed.bam
    ln -s /home/grani/nextflow_work/compil_deseq2/work/6a/ab6592870c925c9fa6e67ab6728f7a/SRR10379725_1_trimmed.bam SRR10379725_1_trimmed.bam
    ln -s /home/grani/nextflow_work/compil_deseq2/work/d2/426ebf5695dd1a139eba022f5351ff/SRR10379722_1_trimmed.bam SRR10379722_1_trimmed.bam
    ln -s /home/grani/nextflow_work/compil_deseq2/work/5f/9484eacbe856f2ab9bb5adbf18123b/SRR10379726_1_trimmed.bam SRR10379726_1_trimmed.bam
    ln -s /home/grani/nextflow_work/compil_deseq2/work/e8/62f3312e868cd820a7b55e5220bb94/SRR10379721_1_trimmed.bam SRR10379721_1_trimmed.bam
    ln -s /home/grani/nextflow_work/compil_deseq2/work/d1/fae1b4cd3f768f333640d8f8d22242/reference.gff reference.gff
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A | tr -d '\r\n')"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/grani/nextflow_work/compil_deseq2/work/18/00c4d88162bc6c2e99dbf9918f133f/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
